[package]
name = "range-set-blaze"
version = "0.1.6"
edition = "2021"
description = "Integer sets as fast, sorted, integer ranges with full set operations"
repository = "https://github.com/CarlKCarlK/range-set-blaze"
readme = "README.md"
documentation = "https://docs.rs/range-set-blaze/latest/range-set-blaze/"
authors = ["Carl Kadie"]
license = "MIT OR Apache-2.0"
keywords = ["set", "range", "data-structures", "btree", "interval"]
categories = ["data-structures"]
homepage = "https://github.com/CarlKCarlK/range-set-blaze"

[workspace]
members = [".", "tests_common", "tests/wasm-demo"]

[lib]

[dependencies]
itertools = "0.13.0"
num-integer = "0.1.44"
num-traits = "0.2.15"
gen_ops = "0.4.0"

[dev-dependencies]
tests_common = { path = "tests_common" }
syntactic-for = "0.1.1"
criterion = { version = "0.5.1", features = ["html_reports"], default-features = false }
trybuild = "1.0.53"
thousands = "0.2.0"
quickcheck = "1.0.3"
quickcheck_macros = "1.0.0"
rangemap = "1.3.0"
range-collections = "0.4.0"
range-set = "0.0.11"
glob = "0.3.0"
thiserror = "1.0"
rand = "0.8.4"
wasm-bindgen-test = "0.3.42"

[target.'cfg(not(target_arch = "wasm32"))'.dev-dependencies]
criterion = { version = "0.5.1", features = ["rayon"] }

[target.'cfg(all(target_arch = "wasm32", target_os = "unknown"))'.dev-dependencies]
getrandom = { version = "0.2", features = ["js"] }
web-time = "1.1.0"

# Declare a benchmark called ""bench" without the standard benchmarking harness. 
[[bench]]
name = "bench"
harness = false

# TODO Rule: for running profiling
# [profile.release]
# debug = true
