[package]
name = "range-set-blaze"
version = "0.1.13"
edition = "2021"
description = "Integer sets as fast, sorted, integer ranges with full set operations"
repository = "https://github.com/CarlKCarlK/range-set-blaze"
readme = "README.md"
documentation = "https://docs.rs/range-set-blaze/latest/range-set-blaze/"
authors = ["Carl Kadie"]
license = "MIT OR Apache-2.0"
keywords = ["set", "range", "data-structures", "no_std", "wasm"]
categories = ["data-structures", "no-std", "wasm"]
homepage = "https://github.com/CarlKCarlK/range-set-blaze"
resolver = "2"
exclude = ["docs/**/*"]


[workspace]
members = [".", "tests_common", "tests/wasm-demo", "tests/embedded"]

[lib]

[features]
default = ["std"]                                                #, "from_slice"]                                  # cmk00
std = ["itertools/use_std", "num-traits/std", "num-integer/std"]
alloc = ["itertools/use_alloc", "num-traits", "num-integer"]
rog-experimental = []
from_slice = []


[dependencies]
itertools = { version = "0.12.0", optional = true, default-features = false }
num-integer = { version = "0.1.44", optional = true, default-features = false }
num-traits = { version = "0.2.15", optional = true, default-features = false }
gen_ops = "0.4.0"

[target.'cfg(not(target_arch = "wasm32"))'.dev-dependencies]
tests_common = { path = "tests_common" }
syntactic-for = "0.1.1"
criterion = { version = "0.5", features = ["html_reports"] }
trybuild = "1.0.53"
thousands = "0.2.0"
quickcheck = "1.0.3"
quickcheck_macros = "1.0.0"
rangemap = "1.3.0"
range-collections = "0.4.0"
range-set = "0.0.10"
glob = "0.3.0"
rand = "0.8.4"
roaring = "0.10.1"

[target.'cfg(target_arch = "wasm32")'.dev-dependencies]
wasm-bindgen-test = "0.3.37"
syntactic-for = "0.1.1"

# Declare a benchmark called ""bench" without the standard benchmarking harness. 
[[bench]]
name = "bench"
harness = false

[package.metadata.docs.rs]
all-features = true

# TODO Rule: for running profiling
# [profile.release]
# debug = true
[profile.release]
opt-level = 3 # Maximum optimization
