[package]
name = "range-set-blaze"
version = "0.1.7"
edition = "2021"
description = "Integer sets as fast, sorted, integer ranges with full set operations"
repository = "https://github.com/CarlKCarlK/range-set-blaze"
readme = "README.md"
documentation = "https://docs.rs/range-set-blaze/latest/range-set-blaze/"
authors = ["Carl Kadie"]
license = "MIT OR Apache-2.0"
keywords = ["set", "range", "data-structures", "btree", "interval"]
categories = ["data-structures"]
homepage = "https://github.com/CarlKCarlK/range-set-blaze"

[workspace]
members = [".", "tests_common"]

[lib]


[dependencies]
itertools = "0.10.1"
num-integer = "0.1.44"
num-traits = "0.2.15"
gen_ops = "0.3.0"
thiserror = "1.0"

[dev-dependencies]
rand = "0.8.4"
tests_common = { path = "tests_common" }
syntactic-for = "0.1.1"
# cmk update
criterion = { version = "0.5.1", features = ["html_reports"] }
trybuild = "1.0.53"
thousands = "0.2.0"
quickcheck = "1.0.3"
quickcheck_macros = "1.0.0"
rangemap = "1.3.0"
range-collections = "0.4.0"
range-set = "0.0.9"
glob = "0.3.0"


# Declare a benchmark called ""bench" without the standard benchmarking harness. 
[[bench]]
name = "bench"
harness = false

# TODO Rule: for running profiling
# [profile.release]
# debug = true
