# cmk may not want this in the project's config
[build]
rustflags = [
    "-C",
    "target-cpu=native",
    #     #     "-C",
    #     #     "target-feature=+avx512f",
    #     #     "-C",
    #     #     "target-feature=+avx512cd",
    #     #     "-C",
    #     #     "target-feature=+avx512bw",
    #     #     "-C",
    #     #     "target-feature=+avx512dq",
    #     #     "-C",
    #     #     "target-feature=+avx512vl",
    #     #     "-C",
    #     #     "target-feature=+avx512ifma",
    #     #     "-C",
    #     #     "target-feature=+avx512vbmi",
    #     #     "-C",
    #     #     "target-feature=+avx512vpopcntdq",
    # "-C",
    # "target-feature=+avx2",
    #     # "-C",
    #     # "target-feature=+avx",
    # "-C",
    # "target-feature=+sse2",
    #     "-C",
    #     "target-feature=+sse",
]
